.PHONY: main
main: *.go deps
	CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o DOORS .


.PHONY:deps
deps:
#	go get github.com/djimenez/iconv-go
#	go get github.com/gorilla/sessions
#	go get github.com/kabukky/httpscerts
#	go get github.com/lib/pq
#	go get golang.org/x/text/encoding
#	go get golang.org/x/text/encoding/unicode






